# Generated by Django 6.0.2 on 2026-02-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
